---
- name: check tar installation
  apt:
    name: tar

- name: check {{ catalina_home }} directory existense
  file:
    path: '{{ catalina_path }}'
    state: directory

- name: unarchive apache-tomcat package
  unarchive:
    src: '{{ apache_tomcat_url }}'
    dest: '{{ catalina_home }}'
    extra_opts:
      - --strip-components=1
    creates: "{{ catalina_home }}/bin"

- name: updating apache-tomcat.service systemd file
  template:
    src: "{{ apache_tomcat_service_template }}"
    dest: /lib/systemd/system/apache-tomcat.service

- name: enabling and starting apache-tomcat service
  systemd:
    name: apache-tomcat
    state: restarted
    enabled: yes
    daemon_reload: yes
